version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      # -- (Optional) Enable Dashboard, don't do in production
      # - "8081:${DASHBOARD_PORT}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${HOST_TRAEFIK_CONFIG}/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "${HOST_TRAEFIK_CONFIG}/conf/:/etc/traefik/conf/"
      - "${HOST_TRAEFIK_CERTS}/certs/:/etc/traefik/certs/"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}  # Cloudflare API token from .env
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
