services:
  traefik:
    image: traefik:latest
    container_name: traefik_v3
    ports:
      - "80:80"
      - "443:443"
      # Optional: Enable Dashboard for testing (maps 8082 on host to 8080 inside container)
      # - "${DASHBOARD_PORT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./config/conf:/etc/traefik/conf:ro"
      - "./config/certs:/etc/traefik/certs:rw"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
