# Global settings
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# EntryPoints for HTTP and HTTPS
entryPoints:
  web:
    address: ":80"
    # Redirect HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    # Optional: You can define custom TLS configurations here, if needed
    # tls:
    #   certResolver: cloudflare

# Certificate Resolvers for Let's Encrypt using Cloudflare DNS Challenge
certificatesResolvers:
  production:
    acme:
      email: "${ACME_EMAIL}"  # Your email from .env file for Let's Encrypt registration
      storage: "/etc/traefik/certs/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Optional: Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem

# Providers for Docker and File
providers:
  docker:
    exposedByDefault: false  # Ensure containers must be explicitly exposed
  file:
    directory: "/etc/traefik/conf"
    watch: true

# (Optional) Enable the API and Dashboard (Insecure set to true is for testing; disable in production)
api:
  dashboard: true
  insecure: false  # Change to true for testing and keep as false for production
