global:
  checkNewVersion: true
  sendAnonymousUsage: false

# -- Configure logging settings --
log:
  level: ERROR
  format: common
  # Optional: Uncomment to write logs to a specific file
  # filePath: /var/log/traefik/traefik.log

# -- Optional: Enable access log --
accesslog:
  format: common
  # Optional: Uncomment to write access logs to a specific file
  # filePath: /var/log/traefik/access.log

# -- Optional: Enable API and Dashboard for testing, disable in production --
# api:
#  dashboard: true
#  insecure: true  # Set to "false" in production

# -- Configure EntryPoints for HTTP and HTTPS --
entryPoints:
  web:
    address: ":80"
    # Optional: Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# -- Configure CertificateResolvers for Let's Encrypt Staging and Production --
certificatesResolvers:
  staging:
    acme:
      email: "your-email@example.com"  # Set your email here
      storage: "/etc/traefik/certs/cloudflare-acme-staging.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
      httpChallenge:
        entryPoint: web
#  production:
#    acme:
#      email: "your-email@example.com"  # Set your email here
#      storage: "/etc/traefik/certs/cloudflare-acme-production.json"
#      caServer: "https://acme-v02.api.letsencrypt.org/directory"
#      httpChallenge:
#        entryPoint: web
#      dnsChallenge:
#        provider: cloudflare
#        resolvers:
#          - "1.1.1.1:53"
#          - "8.8.8.8:53"

# -- Optional: Overwrite Default Certificates --
# tls:
# stores:
#    default:
#      defaultCertificate:
#        certFile: /etc/traefik/certs/cert.pem
#        keyFile: /etc/traefik/certs/cert-key.pem

providers:
  docker:
    exposedByDefault: false  # Ensure containers must be explicitly exposed
  file:
    directory: "/etc/traefik/conf"
    watch: true
