version: "3.8"

services:
  ghost:
    image: ghost:latest
    restart: always
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=ghost
      - database__connection__password=${MYSQL_PASSWORD}
      - database__connection__database=ghostdb
      - url=https://${DOMAIN_NAME}
    volumes:
      - ./ghost_content:/var/lib/ghost/content
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.routers.ghost.tls.certresolver=production"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
    networks:
      - frontend
      - internal
    depends_on:
      db:
        condition: service_healty
# Uncomment the following line for local testing; remove in production where Traefik handles routing.
    # ports:
    #   - "8080:2368"


  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=ghostdb
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  frontend:
    external: true
  internal:
    driver: bridge

volumes:
  ghost_content:
  mysql_data:
